dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 114.55.39.2:2181
  protocol:
    port: 20882

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v17?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  redis:
    host: 114.55.39.2
    port: 6379
    password: java1907

server:
  port: 8080

pagehelper:
  helper-dialect: mysql
  reasonable: true