spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v17?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  redis:
    host: 114.55.39.2
    port: 6379
    password: java1907
  thymeleaf:
    cache: false
  rabbitmq:
    host: 114.55.39.2
    port: 5672
    username: java1907
    password: 123
    virtual-host: /java1907

server:
  port: 9999

mybatis:
  mapper-locations: classpath:/mapper/*.xml
