dubbo:
  application:
    name: web-sso
  registry:
    protocol: zookeeper
    address: 114.55.39.2:2181
server:
  port: 9095
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 114.55.39.2
    port: 5672
    username: java1907
    password: 123
    virtual-host: /java1907