dubbo:
  application:
    name: sms-service
  registry:
    protocol: zookeeper
    address: 114.55.39.2:2181
  protocol:
    port: 20885
server:
  port: 8083

spring:
  rabbitmq:
    host: 114.55.39.2
    port: 5672
    username: java1907
    password: 123
    virtual-host: /java1907
