dubbo:
  application:
    name: web-order
  registry:
    protocol: zookeeper
    address: 114.55.39.2:2181
server:
  port: 9098
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 114.55.39.2
    port: 5672
    username: java1907
    password: 123
    virtual-host: /java1907
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual

alipay:
  serverUrl: https://openapi.alipaydev.com/gateway.do
  appId: 2016101700706609
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCFwnLElz9BtRIoWsI9s+/ZhwF4zdkXptmYfUufzXkbXH2MM3BTGrUO2dJuDg6L8vjBvZ6XmdqUgDBaRj47wy2dDJ9ya8o9trGHqCuMblyKvA0h0vWfmT9zR4mgdXD2aPXbX69dLMrKYvhf7LF3CRv10pcMwgk41GMulHQpsBJDUbJQVN9TzSMMPSMLNGA/k/+Isl1gLMko5+8lxBBkxymsB38Pbj9f5Iz2tAZComFhLiUtAe2kPl7pSZPswoEqig1UzY7Vz0lu0mXqxfz0UTkvt4txFpX649CKF0Yg5tXVwIKDFUtgeESgqvr81r95AMvTB2h3dGJUfNlz2b34LtS5AgMBAAECggEAYREeBioYHo/PUHekc/CLQxlk6QzA2Rgc2js60QnkNAXnmgGOJtC/yboqqfELf2XgPYBkgXGGHLP14t0MtoPKKykI4Jj2V9indmGE0NEZ2Rfkk8IquxoT4I1ug4IWasr6d6s1cHFb7Ijr43i5xD9ZCgg702dQF+yQ2TGkJsh+SFkHZ5yu2w+LZf+H+wxBAwpp1E8gvXOeV9hVYzo4m26o8zwrBBDd95cKydWfKzpjiil/n1/ONWXrf8alft1Y49/AE6ZfJTHw12XSSsU4bnutqIpoJppsKPnyY6INRHnjEtNsQFrIJuBaE1fmNuxkG4AU30NvT9Qzt3/xpIqlVrN9LQKBgQDRS3t9l62Sd5dAwQXxEphWojjngVK0dLO3DfBPBLS+t35YCcfZDC36B4P9v6JhdJGZx+oJuQmYChdn7+u8GSjgavqdwRGPZeqbc+cjt/g9rmF3HbU6qyb3oWfmPHsA0UkaBRc3J5puzGfJyVHue4iUrvCAH77OzJuuxVFy4Di9RwKBgQCjm9B4gsR9rGLu1XyWLuWjtRfOPfP6g6BFnfPDJ0mYPb20Bz/TPAdjnAmZoeptPudCPlW/BMdylZzMSindfmjuq4guaNHeb89cLbiWLbYQ9FbS6fzUOm/6p+f9xD9Z5gNqACMp5oSYI39LHAvt91vupix1CVgJYhVc48nDy5zd/wKBgQCnlYUgH1+AM/oMg4I6ceVBGUvvMwICNJ/iJ2sQGniPbWXhIJPBG5uE5Jevis5+slQTipu/hUZFU29Cbj2Xs52jdIWP45Qn+jdMmhWt6BUBbqvkMQl4HKtrBPaoyCzFjs614vWf2Do0Fb/VNzo/dvL5+sngDYs/E15lJuH81cUY6QKBgQCG9QSmI9hJgmWpdVjr2Yt72unkKp6Syvjt9DkbhdDjUCqn0kMHz8CYniIdJL7nlrfUoO7CPwL2tgs9SP/3wUp1dfFDtxtHTRvTgbN9zf8dRTBJktIHjpzIOrDXV4aadW3jhnF7IrfFd6KNJnmAtkaTOWf6stZ4BvxwP0YzyEWBqQKBgEEbBF2hbF2L17wfFFDtqRcWueRPZnwzbMKe4MOTixmHOV1JWi4IRW3lTRIXvZq8QzF1QeM8qAhyeJmiPnGNhhhlYEBGRJlMvBilm/FUWpVrRm1wBkKnt2lUkW0AUQaU9NMqoVjSI3y1Ot887qSpKKqGjPgHcN8CxbXLBeYNDrXG
  format: json
  charset: utf-8
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr98iOFPcthrEKEr8OlYzj7q1Iz2hkJN/1MmlAIaGJUZrKGUKhr/Ut50+2wY5CB1jur+Fs4UAcxt3A76P26hDOC9+aFX/3SQoAhMFyJq3IQI3qBuWqcXyevyv7su1YMENPdug34PCDiiJbMmIgDWbOyPsMyuB0gMClOymtg+Cbk4N3sFzZBWT7TLBIB3QQ7uzzBaEzSnrJTITgAvDpSaWsgmdnE17hdV11jKjFkd0fdwTxav36czON0bMs1Q/Sbb0E+WeTlI5B6kTD/kVf8Pbzu3URwhdroSF+kr3EP5rd6tsHKZn4Kvv9mc79ks80UhFTmj25TS3aEPz6v5KCPK+RwIDAQAB
  signType: RSA2